baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "arabica"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"

[params]
    description = "A minimal Hugo theme"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "example"
    facebook = "example"