baseurl = "/"
languageCode = "en-us"
title = "Study • Life • Code"
theme = "themes/jane"
#googleAnalytics = ""
#disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#defaultContentLanguage = "zh-cn"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Resume"
    url = "/tianyuzeng-resume.pdf"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/frankzengjj"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/tianyu-zeng-552603114/"

#[Languages.zh-cn]
#  languageCode = "zh-cn"

[params]
    description = "Study"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "example"
    facebook = "example"